---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: company-frontend
    spec:
      containers:
      - name: company-frontend
        image: potatoi9/company-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: backendUrl
          value: http://company
  selector:
    matchLabels:
      app: company-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: company-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: company-frontend